/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inquiries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inquiries */
        get: operations["listInquiries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inquiries/{inquiry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Inquiry */
        get: operations["getInquiry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inquiries/{inquiry_id}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Assignment */
        patch: operations["updateInquiryAssignment"];
        trace?: never;
    };
    "/api/v1/inquiries/{inquiry_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Status */
        patch: operations["updateInquiryStatus"];
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Lead */
        post: operations["createLead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Property */
        get: operations["getProperty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["listAssignees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssigneeChoice */
        AssigneeChoice: {
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "agent";
        };
        /** AssignmentMutation */
        AssignmentMutation: {
            /** Assigneduserid */
            assignedUserId: string | null;
            /** Expectedversion */
            expectedVersion: number;
        };
        /** AttributionInput */
        AttributionInput: {
            /** @default null */
            clickIdKind: components["schemas"]["ClickIdKind"] | null;
            /**
             * Clickidvalue
             * @default null
             */
            clickIdValue: string | null;
            /**
             * Landingurl
             * @default null
             */
            landingUrl: string | null;
            /**
             * Referrerurl
             * @default null
             */
            referrerUrl: string | null;
            /**
             * Utmcampaign
             * @default null
             */
            utmCampaign: string | null;
            /**
             * Utmcontent
             * @default null
             */
            utmContent: string | null;
            /**
             * Utmmedium
             * @default null
             */
            utmMedium: string | null;
            /**
             * Utmsource
             * @default null
             */
            utmSource: string | null;
            /**
             * Utmterm
             * @default null
             */
            utmTerm: string | null;
        };
        /**
         * BudgetBand
         * @enum {string}
         */
        BudgetBand: "300000-400000";
        /**
         * ClickIdKind
         * @enum {string}
         */
        ClickIdKind: "fbclid" | "ttclid" | "twclid";
        /** ConsentInput */
        ConsentInput: {
            /**
             * Admeasurement
             * @default false
             */
            adMeasurement: boolean;
            /**
             * Locale
             * @default en-IN
             */
            locale: string;
            /**
             * Marketing
             * @default false
             */
            marketing: boolean;
            /** Privacynoticeversion */
            privacyNoticeVersion: string;
            /** Requestedcontact */
            requestedContact: boolean;
        };
        /** ConsentSummary */
        ConsentSummary: {
            /** Admeasurement */
            adMeasurement: boolean;
            /** Marketing */
            marketing: boolean;
            /** Noticeversion */
            noticeVersion: string;
            /**
             * Recordedat
             * Format: date-time
             */
            recordedAt: string;
            /** Requestedcontact */
            requestedContact: boolean;
        };
        /** ContactInput */
        ContactInput: {
            /**
             * Email
             * @default null
             */
            email: string | null;
            /** Fullname */
            fullName: string;
            /**
             * Phone
             * @default null
             */
            phone: string | null;
            /** @default null */
            preferredContactMethod: components["schemas"]["PreferredContactMethod"] | null;
        };
        /** ContactResponse */
        ContactResponse: {
            /** Email */
            email: string | null;
            /** Fullname */
            fullName: string;
            /** Phone */
            phone: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryActor */
        HistoryActor: {
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** InquiryDetail */
        InquiryDetail: {
            assignee: components["schemas"]["UserSummary"] | null;
            /** Budgetband */
            budgetBand: string | null;
            /**
             * Capturesurface
             * @constant
             */
            captureSurface: "website";
            consent: components["schemas"]["ConsentSummary"] | null;
            contact: components["schemas"]["ContactResponse"];
            /**
             * Dedupestate
             * @enum {string}
             */
            dedupeState: "clear" | "review";
            /** Formversion */
            formVersion: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Intent */
            intent: ("buy" | "rent" | "sell" | "information") | null;
            /** Message */
            message: string | null;
            /** Preferredcontactmethod */
            preferredContactMethod: ("email" | "phone" | "whatsapp" | "no_preference") | null;
            property: components["schemas"]["PropertySummary"];
            /** Reference */
            reference: string;
            /**
             * Sourceplatform
             * @enum {string}
             */
            sourcePlatform: "facebook" | "instagram" | "tiktok" | "x" | "direct" | "unknown";
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "contacted" | "qualified" | "viewing" | "won" | "lost" | "closed";
            /** Statushistory */
            statusHistory: components["schemas"]["StatusHistoryItem"][];
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
            /** Timeframe */
            timeframe: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Version */
            version: number;
        };
        /** InquiryInput */
        InquiryInput: {
            /** @default null */
            budgetBand: components["schemas"]["BudgetBand"] | null;
            /** @default null */
            intent: components["schemas"]["InquiryIntent"] | null;
            /**
             * Message
             * @default null
             */
            message: string | null;
            /** @default null */
            timeframe: components["schemas"]["Timeframe"] | null;
        };
        /**
         * InquiryIntent
         * @enum {string}
         */
        InquiryIntent: "buy" | "rent" | "sell" | "information";
        /** InquiryPageResponse */
        InquiryPageResponse: {
            /** Items */
            items: components["schemas"]["InquirySummary"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** InquirySummary */
        InquirySummary: {
            assignee: components["schemas"]["UserSummary"] | null;
            contact: components["schemas"]["ContactResponse"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Intent */
            intent: ("buy" | "rent" | "sell" | "information") | null;
            property: components["schemas"]["PropertySummary"];
            /** Reference */
            reference: string;
            /**
             * Sourceplatform
             * @enum {string}
             */
            sourcePlatform: "facebook" | "instagram" | "tiktok" | "x" | "direct" | "unknown";
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "contacted" | "qualified" | "viewing" | "won" | "lost" | "closed";
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
            /** Version */
            version: number;
        };
        /** LeadAccepted */
        LeadAccepted: {
            /**
             * Inquiryid
             * Format: uuid
             */
            inquiryId: string;
            /** Reference */
            reference: string;
            /**
             * Status
             * @constant
             */
            status: "new";
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
        };
        /** LeadRequest */
        LeadRequest: {
            attribution?: components["schemas"]["AttributionInput"];
            consent: components["schemas"]["ConsentInput"];
            contact: components["schemas"]["ContactInput"];
            /** Formversion */
            formVersion: string;
            inquiry?: components["schemas"]["InquiryInput"];
            /** Propertyslug */
            propertySlug: string;
            /**
             * Website
             * @default
             */
            website: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * PreferredContactMethod
         * @enum {string}
         */
        PreferredContactMethod: "email" | "phone" | "whatsapp" | "no_preference";
        /** PropertyResponse */
        PropertyResponse: {
            /** Locality */
            locality: string;
            /** Pricelabel */
            priceLabel: string | null;
            /** Projectregistrationnumber */
            projectRegistrationNumber: string | null;
            /** Registrationauthorityurl */
            registrationAuthorityUrl: string | null;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** PropertySummary */
        PropertySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Absoluteexpiresat */
            absoluteExpiresAt: string;
            /** Displayname */
            displayName: string;
            /** Idleexpiresat */
            idleExpiresAt: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "agent";
            /** Userid */
            userId: string;
        };
        /** StatusHistoryItem */
        StatusHistoryItem: {
            actor: components["schemas"]["HistoryActor"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Fromstatus
             * @enum {string}
             */
            fromStatus: "new" | "contacted" | "qualified" | "viewing" | "won" | "lost" | "closed";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tostatus
             * @enum {string}
             */
            toStatus: "new" | "contacted" | "qualified" | "viewing" | "won" | "lost" | "closed";
        };
        /** StatusMutation */
        StatusMutation: {
            /** Expectedversion */
            expectedVersion: number;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "contacted" | "qualified" | "viewing" | "won" | "lost" | "closed";
        };
        /**
         * Timeframe
         * @enum {string}
         */
        Timeframe: "1-3-months";
        /** UserSummary */
        UserSummary: {
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listInquiries: {
        parameters: {
            query?: {
                pageSize?: number;
                cursor?: string | null;
                status?: ("new" | "contacted" | "qualified" | "viewing" | "won" | "lost" | "closed") | null;
                propertyId?: string | null;
                assignedUserId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryPageResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Role denied */
            403: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getInquiry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inquiry_id: string;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryDetail"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Role denied */
            403: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Inquiry not found */
            404: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateInquiryAssignment: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                inquiry_id: string;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentMutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryDetail"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Role or CSRF denied */
            403: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Inquiry not found */
            404: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stale inquiry version */
            409: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateInquiryStatus: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                inquiry_id: string;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusMutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryDetail"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Role or CSRF denied */
            403: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Inquiry not found */
            404: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stale inquiry version */
            409: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createLead: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listAssignees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssigneeChoice"][];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Role denied */
            403: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Sensitive API responses are private and not stored */
                    "Cache-Control"?: string;
                    /** @description Opaque request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
